config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :achievements
  root 'welcome#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, uniqueness: {
      scope: :user_id,
      message: "you can't have two achievements withe the same title"
  }
  validates :user, presence: true
  enum privacy: [ :public_access, :private_access, :friends_access ]

  mount_uploader :cover_image, CoverImageUploader

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    includes(:user).where("title LIKE ?", "#{letter}%").order("users.email")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :get_achievement, only: [ :show, :edit, :update, :destroy ]
  before_action :owners_only, only: [ :edit, :update, :destroy ]

  def index
    @achievements = Achievement.public_access
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(achievement_params)
    @achievement.user_id = current_user.id

    if @achievement.save
      UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
      redirect_to achievement_path(@achievement), notice: 'Achievement has been created'
    else
      render :new, notice: 'Achievement has not been created'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @achievement.update_attributes(achievement_params)
      redirect_to achievement_path(@achievement.id), notice: 'Achievement has been updated'
    else
      render :edit, notice: 'Achievement has not been updated'
    end
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_path, notice: 'Achievement has been deleted'
  end

  private
  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :feature)
  end

  def get_achievement
    @achievement = Achievement.find(params.fetch(:id))
  end

  def owners_only
    if current_user != @achievement.user
      redirect_to achievements_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/achievements/edit.html.erb
<%= simple_form_for @achievement do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k,_v| [ k.split('_').first.capitalize, k ] }] %>
    <%= f.input :featured, label: 'Features achievement' %>
    <%= f.input :cover_image, as: :file %>

    <%= f.submit 'Update Achievement', class: 'btn btn-primary' %>
<% end %>

app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k,_v| [ k.split('_').first.capitalize, k ] }] %>
  <%= f.input :featured, label: 'Features achievement' %>
  <%= f.input :cover_image, as: :file %>

  <%= f.submit 'Create Achievement', class: 'btn btn-primary' %>
<% end %>

app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<p><%= @achievement.description_html.html_safe %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'New Achievement', new_achievement_path %>
        </li>
      </ul>
    </div>

    <div class="container-fluid">

      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
Welcome